const assert = require('assert');
const fs = require('fs');
const core = require('../assets/js/search-core.js');
const records = JSON.parse(fs.readFileSync('site/assets/data/search-index.json', 'utf8'));
const concepts = JSON.parse(fs.readFileSync('data/114/search-concepts.json', 'utf8'));
const intents = JSON.parse(fs.readFileSync('data/114/search-intents.json', 'utf8'));
const top = (q, scope='all') => core.searchRecords(records, q, concepts, intents, 'all', scope).slice(0, 10);
const contains = (q, re, scope='all') => assert(top(q, scope).some(x => re.test(x.record.title) || re.test(x.record.text)), `${q} missing ${re}`);
contains('青農', /青壯年農民從農貸款/);
contains('買農地', /購買耕地/);
contains('寬限期', /寬緩期/);
contains('農機申請書', /農機/);
assert(/農授金字第0955080181號/.test(top('農授金字第0955080181號', 'all')[0].record.text));
contains('天災', /農業天然災害/);
contains('農企業', /農民組織及農企業/);
contains('電商', /電子商務/);
contains('復耕', /復耕復建/);
contains('週轉金', /週轉金/);
assert(top('常見問題')[0].record.type === '常見問答');
assert(top('申請書', 'all').slice(0, 20).some(x => x.record.type === '書表附件'));
const young = core.searchRecords(records, '青壯年農民', concepts, intents, 'all', 'loan:young-farmer-loan');
assert(new Set(young.map(x => x.record.type)).has('貸款索引'));
assert(new Set(young.map(x => x.record.type)).has('原文頁面'));
assert(new Set(young.map(x => x.record.type)).has('函釋'));
assert(top('青壯年農民', 'section:young-farmer-loan').every(x => x.record.scope === 'section:young-farmer-loan'));
const deterministicA = top('青農').map(x => x.record.id); const deterministicB = top('青農').map(x => x.record.id); const deterministicC = top('青農').map(x => x.record.id);
assert.deepStrictEqual(deterministicA, deterministicB); assert.deepStrictEqual(deterministicB, deterministicC);
for (const query of ['', '   ', '<img src=x onerror=alert(1)>', 'x'.repeat(5000)]) assert.doesNotThrow(() => core.searchRecords(records, query, concepts, intents));
for (const sample of ['１２３ AＢＣ', 'a  \n\tb', '農機🚜申請書']) { const mapped = core.normalizeWithMap(sample); assert(mapped.normalizedText.length >= 1); const range = core.createSnippetRange(sample, [mapped.normalizedText.slice(0, 2)]); assert(range.end <= sample.length); }
assert(!records.some(r => String(r.text).includes('日農授金字第')));
assert(records.filter(r => r.scopeGroup === 'loan:young-farmer-loan').length >= 20);
console.log('SEARCH CORE TEST PASSED: fixed queries, scopes, mapping, determinism, safety and edge cases');
